#!/usr/bin/env bash
# Transfers a file to a server over ssh

if [ $# -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	ARGS=("$@")

	PATH_TO_FILE=${ARGS[0]}
	IP=${ARGS[1]}
	USER=${ARGS[2]}
	PATH_TO_SSH=${ARGS[3]}

	scp -i $PATH_TO_SSH -o 'StrictHostKeyChecking=no' $PATH_TO_FILE $USER"@"$IP':~/'
fi;
