#!/usr/bin/env bash
# Transfers a file to the specified ip. Basically SCP with extra steps
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3@$2:~/"
fi
