#!/usr/bin/env bash
# AUto install and configure nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart

