#!/usr/bin/env bash
# AHHHHHHHHHHHH

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

sudo mkdir -p /var/www/html/
sudo index.html
echo "Holberton School" > index.html

sudo sed s/ "location / {"/ "location /redirect_me {/n return 301 \$scheme://www.youtube.com;" /etc/nginx/sites-available/default

sudo service nginx restart
