#!/usr/bin/env bash
# temp comment

for ((loop=1; loop<101; loop++))
do
	if (( loop % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( loop % 3 == 0 ))
	then	
		echo "Fizz"
	elif (( loop % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $loop
	fi
done
