#!/usr/bin/env bash
# prints 10 times

iter=1
while [ $iter -le 10 ]
do
	if [ $iter -ne 9 ]
	then
		echo "Holberton School"
	else
		echo "Holberton School"
		echo "Hi"
	fi

	iter=$(( iter + 1 ))
done
