#!/usr/bin/env bash
# This script prints "Holberton School" Ten times using a while loop
# But prints "Good luck" on the 8th iteration
# prints "bad luck" on the 4th iteration

loop=0
while [ $loop -ne 10 ]
do
	if [ $loop -eq 7 ]
	then
		echo "good luck"
	elif [ $loop -eq 3 ]
	then
		echo "bad luck"
	else
		echo "Holberton School"
	fi

	loop=$((loop + 1))
done
