#!/usr/bin/env bash
# This script prints 1 - 20
# But prints "bad luck from China" on the 4th iteration
# prints "bad luck from japan on thje 9th iteration
# prints bad luck from italy on the 17th iteration

loop=1
while [ $loop -ne 21 ]
do
	echo $loop

	case "$loop" in
	
	"4")
		echo "bad luck from China"
	;;
	"9")
		echo "bad luck from Japan"
	;;
	"17")
		echo "bad luck from Italy"	
	;;

	esac

	loop=$((loop + 1))

done
