#!/usr/bin/env bash
# over writes the host name file
cp /etc/hosts ~/hosts.new
sed s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed '/127.0.0.2/ i\8.8.8.8	facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
