#!/usr/bin/env bash
# Changes hosts for facebook(yuck) and localhost

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1 localhost/127.0.0.2 localhost/" hosts.new
sed -i -e "s/157.240.11.35 facebook.com/8.8.8.8 facebook.com/" hosts.new
cp -f ~/hosts.new /etc/hosts

