#!/usr/bin/env bash
# Runs Nginx as nginx user (Hopefully :/)
sudo sed -i "s/#user www-data;/user nginx;/g" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
